# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GB_wEv5ZZvrsp_U-y_jRLKdFdzADc6g9
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

from google.colab import files
uploaded=files.upload()

data = pd.read_csv("car-sales-extended.csv")
data

category_featur=["Make","Colour","Doors"]

one_hot=OneHotEncoder()

transformer=ColumnTransformer([("one hot",one_hot,category_featur)],remainder="passthrough")

transformer_data=transformer.fit_transform(data)

y=data['Price']

x_train,x_test,y_train,y_test=train_test_split(transformer_data,y,test_size=0.2)

model=RandomForestRegressor()

model.fit(x_train,y_train)

y_predict=model.predict(x_test)

model.score(x_test,y_test)